[tool.poetry]
name = "sm_vector_store"
version = "0.1.0"
description = "Common Python utilities for ML services; Vector store"
authors = ["Shuming Peh <shuming.peh@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
sm-data-ml-utils = "^1.0.7"
databricks-vectorsearch = "0.67"
joblib = "1.3.2"
loguru = "0.7.0"
pendulum = "3.0.0"
polling = "0.3.2"
python-dotenv = "1.0.0"
tenacity = "9.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
